[package]
name = "rustling-ontology-json-utils"
version = "0.19.0"
authors = ["Hubert De La Jonquiere <hubert.delajonquiere@snips.net>"]

[dependencies]
rustling-ontology-moment = { path="../moment" }
rustling-ontology = { path =".." }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"