[package]
name = "rustling-ontology-it"
version = "0.19.0"
authors = ["hdlj <hubert.delajonquiere@snips.net>"]

[dependencies]
rustling = { git="https://github.com/snipsco/rustling", tag="0.9.0" }
rustling-ontology-moment = { path="../../moment"}
rustling-ontology-values = { path="../../values"}