[package]
name = "rustling-ontology-pt"
version = "0.18.1"
authors = ["hdlj <rosa.stern@snips.ai>"]

[dependencies]
rustling = { git="https://github.com/snipsco/rustling", tag="0.9.0" }
rustling-ontology-moment = { path="../../moment"}
rustling-ontology-values = { path="../../values"}